### ISSUE TITLE
Failing test for DirectedScaleFreeGraphGenerator

### ISSUE THREAD

**Issue by Toptachamann** [jgrapht/jgrapht#853] opened 2020-01-10 20:12 UTC
```
 * JGraphT version: current master branch
 * Java version (java -version)/platform: 8
```

**Issue**
Some of the tests (`DirectedScaleFreeGraphGeneratorTest.testNoOutDegreeZero`) is failing during the continuous integration process. It seems like for some float values generated by the internal random number generator the resulting graph doesn't satisfy the expected condition. 

**The error text:**
`[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.206 s <<< FAILURE! - in org.jgrapht.generate.DirectedScaleFreeGraphGeneratorTest [ERROR] testNoOutDegreeZero(org.jgrapht.generate.DirectedScaleFreeGraphGeneratorTest) Time elapsed: 0.088 s <<< FAILURE! java.lang.AssertionError: expected:<0> but was:<1> at org.jgrapht.generate.DirectedScaleFreeGraphGeneratorTest.testNoOutDegreeZero(DirectedScaleFreeGraphGeneratorTest.java:141)
`

`
[ERROR] Failures: [ERROR] DirectedScaleFreeGraphGeneratorTest.testNoOutDegreeZero:141 expected:<0> but was:<1>
`

**Steps to reproduce (small coding example)**
The problem occurs only for specific random numbers, so it's not possible to reproduce it. 

**Expected outcome**
* We should look into the code logic and understand what the problem is.
* We should modify the tests so that we use the predefined seed in every test to avoid such issues in the future.

The PR has been merged recently, @aalhossary could you please look into this?

**Comment by aalhossary** [comment] 2020-01-10 21:35
I will look into it

**Comment by d-michail** [comment] 2020-01-15 09:20
Until this bug is fixed, we should probably replace the test with one that uses a fixed seed to make it deterministic. Other PRs fail to merge due this one.

**Comment by d-michail** [comment] 2020-01-15 09:24
Also as a debugging strategy, it would make sense to run the failing test with all possible seeds (using a for loop) in order to locate the particular seed which makes the algorithm fail. Then debugging with that particular seed would be easier.

**Comment by aalhossary** [comment] 2020-01-21 00:21
It is not a bug in the generator in the first place. The generator behaves as it should do (adding edges according to a power law). There is no case we are 100% sure the number of (nodes with outDegree == 0) == 0. Even if we set alpha ==1, the generator would only keep adding new nodes, ending in a tree where there is exactly one node with outDegree == 0 in the tree root, which is seed node.

The bug is actually a misdesigned test. The test should allow (the probability) of cases where there are some vertices with outDegree == 0. This probability decreases with decreased alpha value.

If the test is still controversial, we may:

1. rename the test from testNoOutDegreeZero to testProbabilityOfOutDegreeZero.
2. replace it with a star formation test
3. remove the test altogether.

**Comment by aalhossary** [comment] 2020-01-23 09:31
@Toptachamann @d-michail  So, what are we going to do?
[Accept / rename / replace/ remove the test]

**Comment by jsichi** [comment] 2020-01-29 15:23
@aalhossary please implement the suggestion from @d-michail to use a fixed seed so that other PR's are not affected by the non-deterministic broken build...this is a completely unacceptable situation which needs to be resolved as super-high priority.

**Comment by jsichi** [comment] 2020-02-04 11:42
@aalhossary please fix this per my comment above.  This is blocking other PR's from being merged.

**Comment by aalhossary** [comment] 2020-02-05 02:13
@jsichi  OK, I fixed it as per your request.
However, I believe it is better to amend the test or remove it (the test) altogether.

**Closed** 2020-02-17 11:26 UTC
Labels: bug
