### ISSUE TITLE
PushRelabelMFImpl MIn s-t Cut not terminating

### ISSUE THREAD

**Issue by Aimmig** [jgrapht/jgrapht#620] opened 2018-07-07 14:33 UTC
I'm currenlty using jgrapht for implemenation on my thesis, and have come accross the following problem:
In some cases calling calculateMinCut(s,t) on a instance of PushRelabelMFImpl seems to never return.
Replacing PushRelabel with EdmondsKarp works, but on large graphs it so slow :/
As types for the graph to operate on i currently use SimpleDirectedWeightedGraph (as the doc says that this is supported).
This might be related to very small edge weights (in my case all weights are within 0 to 1)

**Comment by AlexandruValeanu** [comment] 2018-07-08 10:59
Can you please post a graph (the smaller the better) on which it fails to terminate?

**Comment by Aimmig** [comment] 2018-07-08 14:06
Below is an example that reproduces the problem, when calculating
a MinCut with s=-1 and t=-2

#Edge and vertex sets
([-1, -2, 0, 1], [(-1,0), (0,-2), (-1,1), (1,-2), (0,1), (1,0)])
# directed edges with weights
-1 0 1.0
0 -2 0.9999999999999999
-1 1 1.0
1 -2 1.66498
0 1 0.66498
1 0 0.66498

My input graphs almost certainly will have a cycle (so i need to use weighted Directed Graphs),
so that might be the problem as stated here
https://jgrapht.org/javadoc/org/jgrapht/alg/flow/PushRelabelMFImpl.html

**Comment by AlexandruValeanu** [comment] 2018-07-08 22:21
@Aimmig Because you are using really small weights the algorithms keeps expanding the same vertex which has excess `1.1102230246251565E-16`. The fix for this problem is simple. Can you please replace [this line](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/alg/flow/PushRelabelMFImpl.java#L528) with `return excess > 1e-9;1 and check that the problem is solved?

For me it stops with minCutCapacity=2 on the above example but I want to make sure that it works on all your cases before I submit a PR to actually fix it.

**Comment by Aimmig** [comment] 2018-07-09 12:11
Thanks, that seems to fix the issue. I did some testing and all cases that had the problem seem to run fine now.

**Comment by AlexandruValeanu** [comment] 2018-07-09 14:23
Great. I'll submit a PR to fix this issue. Thank you for reporting it.

**Closed** 2018-07-10 11:01 UTC
Labels: bug
