### ISSUE TITLE
Compile-time error while running HelloJGraphT.java

### ISSUE THREAD

**Issue by apoorv-mishra** [jgrapht/jgrapht#373] opened 2017-03-08 11:50 UTC
Hi, I am new to open-source. I am using Ubuntu 14.04 LTS. I forked jgrapht and then cloned it into my IntelliJ IDEA 2016.3.4. Then I tried to run HelloJGraphT.java. But it failed and displayed about a hundred error messages. The very first error that was displayed is as shown:

**/home/apoorv/IdeaProjects/jgrapht/jgrapht-io/src/main/java/org/jgrapht/io/DOTImporter.java**
        Error:(188, 17) java: cannot find symbol
        symbol:   class DOTBaseListener
        location: class org.jgrapht.io.DOTImporter<V,E>

How do I fix this?

**Comment by d-michail** [comment] 2017-03-08 12:25
Duplicate of #353. See the [wiki](https://github.com/jgrapht/jgrapht/wiki/Contributor-Guidelines) on how to use IntelliJ.

Short version:
Right click on the jgrapht-io project and run Maven->Generate Sources and Update Folders

**Comment by apoorv-mishra** [comment] 2017-03-08 18:11
I followed the [wiki](https://github.com/jgrapht/jgrapht/wiki/Contributor-Guidelines). It didn't work. Although when I ran ```mvn test```, it worked.

**Comment by jkinable** [comment] 2017-03-08 18:26
The fact that mvn test works indeed confirms that this is an intellij related issue.

Did you try this:

1. in the directory with the source files, run the command: mvn test
This will compile all the code using maven.
2. In intellij under project structure, right click the 'org' folder under jgrapht-ext>target>generated-sources>antlr4. Select Mark directory as -> sources root.

"It didn't work" isn't very informative. What exactly is the result?

**Comment by d-michail** [comment] 2017-03-08 23:38
I just tested the wiki instructions with IntelliJ 2016.3.5 and they work perfectly.

Anyway, this is an IntelliJ issue w.r.t. their maven support. We cannot really do anything other than provide the wiki instructions.

**Comment by apoorv-mishra** [comment] 2017-03-09 06:25
I apologize for being sloppy while mentioning the details. By the way, here's what I did:

1. In the directory with the source files, I ran the command: ```mvn test```. This, I think, compiled all the code using maven since I noticed a "target" folder containing related .class files in each of the projects jgrapht-core, jgrapht-demo, jgrapht-ext and jgrapht-io.

2. In IntelliJ under project structure, I right clicked the 'org' folder under jgrapht-io>target>generated-sources>antlr4. I marked it as "Sources". But as I clicked on the "apply" button, a dialog titled "Cannot save settings" appeared on the screen which displayed a message that said- **Source root "/home/apoorv/jgrapht/jgrapht-io/target/generated-sources/antlr4/org"
cannot be defined in module "jgrapht" because it belongs to content of nested module "jgrapht-io"**. So, I unmarked the 'org' folder as "Sources".

3. Then I tried to run HelloJGraphT.java since I noticed HelloJGraphT.class file in the project explorer window and it worked perfectly fine displaying the intended output.

P.S - I couldn't find any 'antlr4' folder under jgrapht-ext>target>generated-sources. I could only find jgrapht-ext>target>generated-sources>annotations.

**Comment by d-michail** [comment] 2017-03-09 07:15
The `antlr` folder is now at location `jgrapht-io>target>generated-sources>antlr4`. 

If you follow the wiki instructions to the point, by right clicking on the jgrapht-io project and running `Maven->Generate Sources and Update Folders` it is marked as source automatically. This means that your IntelliJ must have Maven support enabled.  

Otherwise use that folder and do what @jkinable suggested by using `Select Mark directory as -> sources root`.

**Comment by apoorv-mishra** [comment] 2017-03-09 07:26
Okay, Thanks for the help :+1:

**Comment by d-michail** [comment] 2017-03-10 11:18
Thanks for reporting! Let us hope that the upcoming IntelliJ 2017.1 fixes this.

**Closed by d-michail** 2017-03-10 11:18 UTC
