### ISSUE TITLE
GraphMLImporter fails when SAX parser calls method `characters()` multiple times

### ISSUE THREAD

**Issue by nikelback** [jgrapht/jgrapht#644] opened 2018-07-27 11:49 UTC
When importing the attached .grapml file, it occurs that the "currentData" is not properly written.
The issue occurs on node v14 where the value of "key1"  is split.

```
Graph<V, E> g = new Graph<>();
GraphMLImporter<V, E> imp = new GraphMLImporter<>(vProvider, eProvider)); 

File file = new File("failOn_v14_coordinates.graphml");
byte[] fileBytes = Files.readAllBytes(Paths.get(file.getAbsolutePath()));
StringReader sr = new StringReader(new String(fileBytes, "UTF-8"));

imp.importGraph(g, sr);
```

The original coordinates of "v14" should be (1820.375, 1068.38452)
It appears that the Importer is calling the GraphMLHandler.characters() twice for "key1".
The value is split into  "10"  and "68.38452".

This may be the result of a bug in the XmlReader / SaxParser, which is calling the characters()-method, but I could resolve the problem in two ways:
First:
Initializing the currentData with empty string in line
```487:  currentData = new Data(findAttribute(DATA_KEY, attributes), "");```
and then appending values in the characters() method
```552: currentData.value += new String(ch, start, length);```

Second:
Using an InputSource with an InputStream instead of a Reader does not produce the issue.

```
@Override
public void importGraph(Graph<V, E> graph, InputStream is) throws ImportException {
	try {
		// parse
		XMLReader xmlReader = createXMLReader();
		GraphMLHandler handler = new GraphMLHandler();
		xmlReader.setContentHandler(handler);
		xmlReader.setErrorHandler(handler);
		xmlReader.parse(new InputSource(is));   // using InputStream instead of Reader
		// read result
		handler.updateGraph(graph);
	} catch (Exception se) {
		throw new ImportException("Failed to parse GraphML", se);
	}
}
```

[failOn_v14_coordinates.graphml.zip](https://github.com/jgrapht/jgrapht/files/2235562/failOn_v14_coordinates.graphml.zip)

**Comment by d-michail** [comment] 2018-07-27 14:32
I am not able to reproduce this. There must be something wrong with your system, setup, libraries, operating system, etc. 

I tried the following code with JGraphT version `1.2.0`.

```
package org.myorg.mycode;

import java.io.File;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Paths;

import org.jgrapht.Graph;
import org.jgrapht.graph.DefaultEdge;
import org.jgrapht.graph.builder.GraphTypeBuilder;
import org.jgrapht.io.EdgeProvider;
import org.jgrapht.io.GraphMLImporter;
import org.jgrapht.io.VertexProvider;
import org.jgrapht.util.SupplierUtil;

public class App {
	
	public static void main(String[] args) throws Exception {
		
		Graph<String, DefaultEdge> graph = GraphTypeBuilder
				.undirected()
				.allowingMultipleEdges(true)
				.allowingSelfLoops(true)
				.vertexSupplier(SupplierUtil.createStringSupplier())
				.edgeSupplier(SupplierUtil.createDefaultEdgeSupplier())
				.buildGraph();
		
		VertexProvider<String> vp = (id, attributes) -> {
			System.out.println("Creating node " + id);
			for(String key: attributes.keySet()) { 
				System.out.println("key: " + key + ", value: " + attributes.get(key));
			}
			return id;
		};
		EdgeProvider<String, DefaultEdge> ep = (from, to, label, attributes) -> {
			System.out.println("Creating edge from " + from + " to " + to);
			for(String key: attributes.keySet()) { 
				System.out.println("key: " + key + ", value: " + attributes.get(key));
			}
			return new DefaultEdge();
		};
		
		GraphMLImporter<String, DefaultEdge> importer = new GraphMLImporter<>(vp, ep);

		File file = new File("failOn_v14_coordinates.graphml");
		byte[] fileBytes = Files.readAllBytes(Paths.get(file.getAbsolutePath()));
		StringReader sr = new StringReader(new String(fileBytes, "UTF-8"));
		
		importer.importGraph(graph, sr);
		
	}
	
}
```

and I am getting the following output 

```
Creating node v30
key: y, value: 1577.70386
key: x, value: 348.9343
key: VertexLabel, value: v30
Creating node v21
key: y, value: 894.96509
key: x, value: 529.51923
key: VertexLabel, value: v21
Creating node v20
key: y, value: 1319.21033
key: x, value: 1551.89807
key: VertexLabel, value: v20
Creating node v31
key: y, value: 658.2821
key: x, value: 2346.39087
key: VertexLabel, value: v31
Creating node v12
key: y, value: 548.948
key: x, value: 2372.37598
key: VertexLabel, value: v12
Creating node v23
key: y, value: 2299.06421
key: x, value: 131.28847
key: VertexLabel, value: v23
Creating node v22
key: y, value: 923.13416
key: x, value: 439.07156
key: VertexLabel, value: v22
Creating node v14
key: y, value: 1068.38452
key: x, value: 1820.375
key: VertexLabel, value: v14
Creating node v25
key: y, value: 1391.38745
key: x, value: 445.43762
key: VertexLabel, value: v25
Creating node v13
key: y, value: 1604.89478
key: x, value: 254.37254
key: VertexLabel, value: v13
Creating node v27
key: y, value: 1535.09082
key: x, value: 426.58652
key: VertexLabel, value: v27
Creating node v15
key: y, value: 585.14844
key: x, value: 2263.01416
key: VertexLabel, value: v15
Creating node v26
key: y, value: 1128.46667
key: x, value: 681.97986
key: VertexLabel, value: v26
Creating node v18
key: y, value: 834.38361
key: x, value: 2313.37866
key: VertexLabel, value: v18
Creating node v29
key: y, value: 873.71802
key: x, value: 541.58197
key: VertexLabel, value: v29
Creating node v17
key: y, value: 991.72327
key: x, value: 1595.68872
key: VertexLabel, value: v17
Creating node v28
key: y, value: 976.92627
key: x, value: 1771.12268
key: VertexLabel, value: v28
Creating node v19
key: y, value: 441.26508
key: x, value: 2281.87378
key: VertexLabel, value: v19
Creating edge from v31 to v12
key: EdgeLabel, value: e0
key: weight, value: 112.37958606669669
Creating edge from v21 to v22
key: EdgeLabel, value: e1
key: weight, value: 94.73266339069012
Creating edge from v20 to v14
key: EdgeLabel, value: e2
key: weight, value: 367.4145463973644
Creating edge from v22 to v25
key: EdgeLabel, value: e3
key: weight, value: 468.2965623573888
Creating edge from v23 to v13
key: EdgeLabel, value: e4
key: weight, value: 704.9970821459403
Creating edge from v30 to v13
key: EdgeLabel, value: e5
key: weight, value: 98.39345803834726
Creating edge from v30 to v27
key: EdgeLabel, value: e6
key: weight, value: 88.57617314475725
Creating edge from v25 to v27
key: EdgeLabel, value: e7
key: weight, value: 144.93454564239295
Creating edge from v12 to v15
key: EdgeLabel, value: e8
key: weight, value: 115.19756737842133
Creating edge from v31 to v15
key: EdgeLabel, value: e9
key: weight, value: 110.90630277590041
Creating edge from v20 to v26
key: EdgeLabel, value: e10
key: weight, value: 890.5845473169853
Creating edge from v25 to v26
key: EdgeLabel, value: e11
key: weight, value: 353.66589863885093
Creating edge from v21 to v26
key: EdgeLabel, value: e12
key: weight, value: 278.86776716302893
Creating edge from v31 to v18
key: EdgeLabel, value: e13
key: weight, value: 179.1690482013124
Creating edge from v14 to v18
key: EdgeLabel, value: e14
key: weight, value: 545.7188238041855
Creating edge from v21 to v29
key: EdgeLabel, value: e15
key: weight, value: 24.43251276255677
Creating edge from v26 to v17
key: EdgeLabel, value: e16
key: weight, value: 923.884537313002
Creating edge from v20 to v17
key: EdgeLabel, value: e17
key: weight, value: 330.4018696903306
Creating edge from v14 to v28
key: EdgeLabel, value: e18
key: weight, value: 103.87686228629025
Creating edge from v17 to v28
key: EdgeLabel, value: e19
key: weight, value: 176.0568815192452
Creating edge from v12 to v19
key: EdgeLabel, value: e20
key: weight, value: 140.66363945443177
Creating edge from v15 to v19
key: EdgeLabel, value: e21
key: weight, value: 145.11411561744777
```

where `v14` has the correct values.

**Comment by nikelback** [comment] 2018-07-30 10:15
Hi Dimitrios,

i did use your code again and came out with the wrong value for v14.
As i mentioned, the source of the problem may be the SaxParser / XmlReader implementation created by the SaxParserFactory.
I did check, that my system uses
saxParser: org.apache.xerces.jaxp.SAXParserImpl
xmlReader:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser

Since it is the Reader, which is calling the characters() method, something is wrong there, not in the GraphMLImporter.
I logged the  calls to the method and it looks like the Readers Position is resetted there.  (I assume buffer size is 2048)

characters           - VALUE=v14   start=1973   length=3
characters           - VALUE=1820.375   start=2007   length=8
characters           - VALUE=10   start=2046   length=2
characters           - VALUE=68.38452   start=0   length=8

If this Problem occurs with other Reader impl. in the future as well, the first solution would overcome this.
Nonetheless it is actually a user problem

Thanks for your response.
Nikelback :)



Creating node v30
key: y, value: 1577.70386
key: x, value: 348.9343
key: VertexLabel, value: v30
Creating node v21
key: y, value: 894.96509
key: x, value: 529.51923
key: VertexLabel, value: v21
Creating node v20
key: y, value: 1319.21033
key: x, value: 1551.89807
key: VertexLabel, value: v20
Creating node v31
key: y, value: 658.2821
key: x, value: 2346.39087
key: VertexLabel, value: v31
Creating node v12
key: y, value: 548.948
key: x, value: 2372.37598
key: VertexLabel, value: v12
Creating node v23
key: y, value: 2299.06421
key: x, value: 131.28847
key: VertexLabel, value: v23
Creating node v22
key: y, value: 923.13416
key: x, value: 439.07156
key: VertexLabel, value: v22

Creating node v14
key: y, value: 68.38452
key: x, value: 1820.375
key: VertexLabel, value: v14

Creating node v25
key: y, value: 1391.38745
key: x, value: 445.43762
key: VertexLabel, value: v25
Creating node v13
key: y, value: 1604.89478
key: x, value: 254.37254
key: VertexLabel, value: v13
Creating node v27
key: y, value: 1535.09082
key: x, value: 426.58652
key: VertexLabel, value: v27
Creating node v15
key: y, value: 585.14844
key: x, value: 2263.01416
key: VertexLabel, value: v15
Creating node v26
key: y, value: 1128.46667
key: x, value: 681.97986
key: VertexLabel, value: v26
Creating node v18
key: y, value: 834.38361
key: x, value: 2313.37866
key: VertexLabel, value: v18
Creating node v29
key: y, value: 873.71802
key: x, value: 541.58197
key: VertexLabel, value: v29
Creating node v17
key: y, value: 991.72327
key: x, value: 1595.68872
key: VertexLabel, value: v17
Creating node v28
key: y, value: 976.92627
key: x, value: 1771.12268
key: VertexLabel, value: v28
Creating node v19
key: y, value: 441.26508
key: x, value: 2281.87378
key: VertexLabel, value: v19

<edges>


On 28. Jul 2018, at 13:16, Dimitrios Michail <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #644<https://github.com/jgrapht/jgrapht/issues/644>.

**Comment by d-michail** [comment] 2018-07-31 07:30
Thanks for the debugging and the explanation. I did a quick search and what you are experiencing is a valid parser implementation. I opened up #647 with a fix.

In my system this never really happens. Could you test the parser? If possible could you also test class `SimpleGraphMLImporter` which is a simpler but faster implementation?

**Comment by d-michail** [comment] 2018-08-03 16:54
Closing this as the fix was merged. Feel free to reopen if the problem persists.

**Closed by d-michail** 2018-08-03 16:54 UTC

**Comment by LahaLuhem** [comment] 2020-09-26 11:34
I get a error on just a sinlge line using code provided by @d-michail:

cannot infer type arguments for GmlImporter<>
  reason: cannot infer type-variable(s) V,E
    (actual and formal argument lists differ in length)
  where V,E are type-variables:
    V extends Object declared in class GmlImporter
    E extends Object declared in class GmlImporter

maybe I'm using newer libraries?
