### ISSUE TITLE
Querying

### ISSUE THREAD

**Issue by weaver159** [jgrapht/jgrapht#404] opened 2017-05-18 11:11 UTC
How about a package the allows querying the graph for vertices/edges. Not an query language but rather a simple api that allows you to retrieve sets of vertices/edges that meet certain criteria, like they have some attributes, satisfy some connectivity properties and stuff like that.  

Also, additional to the above, a class that allows modification of the vertices/edges of a graph already defined would also be interesting. I saw that there was a VerterUpdater but it seems to be depreciated.

If you wanna think in SQL terms, the above would be the "select" and "update" commands. If there's interest in this it can latter be expanded to more complicated queries.

Anyone find this interesting?

**Comment by d-michail** [comment] 2017-05-18 13:41
Duplicate of #166. See [Apache TinkerPop](https://tinkerpop.apache.org/) for more details and a well defined API for what you are suggesting.

We currently have no manpower to start such an endeavor. If you feel confident enough, contributions are welcomed. See [JanusGraph](http://janusgraph.org/) for an open-source graph database which supports the TinkerPop API.

**Closed** 2017-05-24 04:32 UTC
