### ISSUE TITLE
Invalid handle exception in jheaps when computing shortest paths using A* algorithm

### ISSUE THREAD

**Issue by ishanSharma07** [jgrapht/jgrapht#908] opened 2020-04-14 08:42 UTC
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform:  openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~19.10-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

**Issue**
I am generating a large graph (that represents a three-dimensional lattice) with around 2 million vertices and 50 million edges. Just to measure the performance of A* I wrote a function that generates random source and target vertices and finds the shortest path between them. 
I tried to run it for around 5000 iterations but after around 200 iterations I encounter the following error:
```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid handle!
	at org.jheaps.tree.PairingHeap.decreaseKey(PairingHeap.java:426)
	at org.jheaps.tree.PairingHeap.access$000(PairingHeap.java:90)
	at org.jheaps.tree.PairingHeap$Node.decreaseKey(PairingHeap.java:364)
	at org.jgrapht.alg.shortestpath.AStarShortestPath.expandNode(AStarShortestPath.java:224)
	at org.jgrapht.alg.shortestpath.AStarShortestPath.getPath(AStarShortestPath.java:172)
	at com.dreamlab.lattice3.LatticeGenerator$CustomGraph.randomAstar(LatticeGenerator.java:593)
	at com.dreamlab.lattice3.LatticeGenerator.main(LatticeGenerator.java:684)
```
Any idea what could be causing this? I can't seem to figure it out.

**Steps to reproduce (small coding example)**
I guess generate a large graph and repeatedly execute A* algorithm on a bunch of source and target vertices.

**Expected behaviour**
Should compute the path without encountering the above error.

**Other information**
* I had set Xmx to 12GB and when this error occurred there was around 5 GB of heap memory available
* Not sure if it would help but, if the function sleeps for about 1 second after computing the path then I can push it to around 500 iterations before I encounter the above error.
* I had no problem executing Dijkstra's for around 5000 iterations with random source and destination vertices.

**Comment by d-michail** [comment] 2020-04-15 06:47
We need a reproducible example in order to debug the issue. This means that you need to share the code (or a small snippet) that generates the graph, and the source and targets vertices. 

Otherwise, if it is that simple as you describe like "generate a large graph and repeatedly execute A* on a bunch of source and target vertices", you could instead write a small unit test method which does exactly what you describe.

**Comment by d-michail** [comment] 2020-04-26 06:52
Closing until the reporter provides the necessary code which reproduces this.

Problems like this might occur due to some bug in the library, or due to some bug in the user code. In order to be certain that the user code has not bugs, we request that the user provides a reproducible example.

**Closed by d-michail** 2020-04-26 06:52 UTC

**Comment by tomeeeS** [comment] 2021-03-25 11:54
Can I just leave a comment about a possible mistake on user's end here, as I've just experienced this:
I was using an unweighted graph while I needed to have used a weighted one, so all my edges had weight 1 and was using a heuristic that assumed otherwise. 
Basically I did not realize I had not explicitly told Jgrapht about the weight values in my edge class.

**Comment by jacksonneal** [comment] 2021-06-14 14:27
@ishanSharma07 any chance you were able to resolve this issue?  I am experiencing the same.  I am using a DefaultDirectedWeightedGraph.

**Comment by ishanSharma07** [comment] 2021-06-14 14:58
@jacksonneal Unfortunately because of covid our priorities changed and I had switched organizations before I could get back to this.
