### ISSUE TITLE
NaiveLCAFinder.getLCASet may include common but not lowest ancestors

### ISSUE THREAD

**Issue by sh5i** [jgrapht/jgrapht#840] opened 2019-11-23 03:10 UTC
```
 * JGraphT version: 1.3.1
 * Java version (java -version)/platform:
java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode) 
```

**Issue**
The result of `NaiveLCAFinder.getLCASet` may include common but not lowest ancestors.

The fault seems to be:
https://github.com/jgrapht/jgrapht/blob/a8e7fddd579cce683313a312c7ca9d753bcbd0bc/jgrapht-core/src/main/java/org/jgrapht/alg/lca/NaiveLCAFinder.java#L157

This code checks only the *direct* parents (not ancestors) of each candidate when detecting non-lowest (non-leave) common ancestors; it may miss finding some non-leave ancestors if there is an intermediate vertex between two candidates (e.g., `"x"` in the following example).

**Steps to reproduce (small coding example)**
Test.java:
```
import org.jgrapht.alg.lca.NaiveLCAFinder;
import org.jgrapht.graph.DirectedAcyclicGraph;
public class Test {
    public static void main(String[] args) {
        DirectedAcyclicGraph<String, Object> g = new DirectedAcyclicGraph<>(Object.class);
        //   root
        //   / | \
        //  |  x  |
        //  |  |  |
        //  | lca |
        //  |/   \|
        //  a     b
        g.addVertex("root");
        g.addVertex("x");
        g.addVertex("lca");
        g.addVertex("a");
        g.addVertex("b");
        g.addEdge("root", "x");
        g.addEdge("x", "lca");
        g.addEdge("lca", "a");
        g.addEdge("lca", "b");
        g.addEdge("root", "a");
        g.addEdge("root", "b");
        NaiveLCAFinder<String, Object> finder = new NaiveLCAFinder<>(g);
        System.out.println(finder.getLCASet("a", "b"));
    }
}
```

```
$ javac -cp jgrapht-core-1.3.1.jar Test.java
$ java -cp .:jgrapht-core-1.3.1.jar Test
[lca, root]
```

**Expected behaviour**
```
[lca]
```

**Comment by d-michail** [comment] 2019-11-23 08:24
Why are you creating a second issue? This is the same as #839.

**Comment by sh5i** [comment] 2019-11-23 08:26
No, this is another and different issue for `NaiveLCAFinder.getLCASet`. #839 is for `NaiveLCAFinder.getLCA`.

**Comment by sh5i** [comment] 2019-11-23 08:31
If I understood correctly, `getLCA` and `getLCASet` are implemented independently, and either of them have an independent issue.

**Comment by d-michail** [comment] 2019-11-26 13:36
No point in having two almost identical issues. Decide which you prefer to keep and close the other. Thanks.

**Comment by d-michail** [comment] 2019-11-30 07:43
Duplicate of #839.

**Closed by d-michail** 2019-11-30 07:43 UTC
