### ISSUE TITLE
SuurballeKDisjointShortestPaths getPaths non deterministic output

### ISSUE THREAD

**Issue by andreamarotta** [jgrapht/jgrapht#943] opened 2020-06-08 19:27 UTC
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform: 1.8.0_201
```

**Issue**
After constructing SuurballeKDisjointShortestPaths<Integer,DefaultWeightedEdge> passing to the constructor an instance of a SimpleDirectedWeightedGraph<Integer, DefaultWeightedEdge>,
the execution of the method getPaths(i,j,k)  has the following issues:

- the returned shortests paths from node i to j have different costs with respect to the ones from j to i
- returns paths with different costs when executing in Run and Debug environment (Eclipse IDE)

**Steps to reproduce (small coding example)**
I'm attaching a graph instance with 53 vertices and 158 edges and java code that loads the graph and runs the algorithm.
It calculates the k shortest disjoint paths from node 0 to node 38 and from node 38 to 0 and shows that they differ in terms of cost. 
The sum of the cost of the first 2 paths should match and it does not.

**Expected behaviour**
It should always return the same set of k shortest paths and this set should be sorted by cost (number of hops with edges unitary cost).
As the sum of the cost of the first two disjoint paths from i to j differes from the one from j to i, trivially, the list returned does not represent the k **shortest** disjoint paths.

**Other information**
As the graph is directed, the attached code checks bidirectionality of the links which is a necessary condition to have same cost for i->j and j->i
[Bug_Suurballe.zip](https://github.com/jgrapht/jgrapht/files/4748092/Bug_Suurballe.zip)

**Comment by jsichi** [comment] 2020-06-12 02:14
I can confirm that I see the incorrect behavior; as you've observed, the results are non-deterministic (even across multiple runs from the command line).

Run 1:

(0,38) weights: 10.0
Working:
[0, 1, 2, 41, 39, 38]
5.0
Backup:
[0, 14, 27, 34, 36, 38]
5.0
(38,0) weights: 10.0
Working:
[38, 39, 2, 1, 0]
4.0
Backup:
[38, 40, 39, 41, 2, 3, 0]
6.0

Run 2:

(0,38) weights: 8.0
Working:
[0, 3, 34, 36, 38]
4.0
Backup:
[0, 1, 2, 39, 38]
4.0
(38,0) weights: 10.0
Working:
[38, 36, 34, 27, 14, 0]
5.0
Backup:
[38, 40, 39, 2, 3, 0]
5.0

I've rendered the input graph below; all the weights are 1.0.

![test](https://user-images.githubusercontent.com/632737/84457358-4b8d5400-ac17-11ea-99f2-cfb6820ec41a.png)

**Comment by jsichi** [comment] 2020-06-12 02:15
@assimiz could you take a look at this one?

**Comment by assimiz** [comment] 2020-06-14 15:27
Checking.

**Comment by assimiz** [comment] 2020-06-15 06:37
The problem is with the stitching of the paths from the valid edges. Valid edges should be taken from the paths in FIFO method. So, if we are currently at node `u` and we have two outgoing edges from it - `(u, v)` and` (u, w)`, we should take the edge discovered earlier (i.e. for the lowest `k` path). This is why `ArrayDeque `was used in the previous implementation. Current implementation is doing exactly the opposite taking the last edge from the list (line 200, probably to save array shifts). So, just removing the first element in the list instead of the last is giving me deterministic output for this input. However, disregarding performance for a moment, I am not sure it is enough as the order coming from valid edges may not be preserved twice. Once from the `validEdges.values()` at line 225 and second from `Collectors.groupingBy` at line 188. Please comment on this last statement.

Your general comments would also be appreciated.
My apologies for missing that review back then. Would have catch it (probably).
I will soon open a PR to fix it.

**Comment by jsichi** [comment] 2020-06-16 04:56
I'm not sure exactly which collections need determinism and which don't here, but anywhere you want to guarantee determinism, use LinkedHashMap/Set instead of HashMap/Set.

Collectors.groupingBy preserves order (whereas Collectors.groupingByConcurrent does not).

**Comment by assimiz** [comment] 2020-06-16 13:05
@jsichi thanks for your input.
validEdges needs determinism.

**Comment by jsichi** [comment] 2020-06-23 04:42
@andreamarotta the fix has been merged; you should be able to pick it up in the latest SNAPSHOT build

**Closed** 2020-06-23 04:43 UTC
Labels: bug
